### create account
POST http://localhost:8080/account
Content-Type: application/json

{"userId" : "10", "initialBalance": 10000}

<> 2022-06-20T175149.200.json
<> 2022-06-13T014502.200.json

### delete account
DELETE http://localhost:8080/account
Content-Type: application/json

{"userId" : "10", "accountNumber": 1000000000}

<> 2022-06-13T014502.404.json

### inquire account
GET http://localhost:8080/account?user_id=10

<> 2022-06-13T014502-1.200.json

### transaction use
POST http://localhost:8080/transaction/use
Content-Type: application/json

{"userId": 10,"accountNumber": 1000000000,"amount": 1000}

<> 2022-06-13T014502-2.200.json

### transaction cancel
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{"transactionId": "a8ef03e143754319bb40e58fa920263d", "accountNumber": 1000000003,"amount": 5500}

<> 2022-06-13T014503-1.404.json

### transaction inquiry
GET http://localhost:8080/transaction/ba99c4f0517d41db986b171fa25306b3

<> 2022-06-13T014503-1.200.json
<> 2022-06-13T014327-3.200.json
